version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
    env_file:
      - .env.test
    depends_on:
      - mongo-test
      - redis-test

  mongo-test:
    image: mongo:latest
    ports:
      - "27018:27017"

  redis-test:
    image: redis:alpine
    ports:
      - "6380:6379"
